name: Synchroniser le Hub

on:
  repository_dispatch:
    types: [update-hub]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "✅ GitHub Actions fonctionne"
